---
imports:
  - {resource: ./controllers.yaml}
  - {resource: ../../main/financial/shared/infrastructure/di/services.yaml}

services:
  Shared.MongoConfig:
    factory:
      class: ../../main/shared/infrastructure/mongo/MongoConfigFactory
      method: 'createConfig'

  Shared.ConnectionManager:
    factory:
      class: ../../main/shared/infrastructure/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['@Shared.MongoConfig']

  Shared.SequelizeConfig:
    factory:
      class: ../../../main/shared/infrastructure/sequelize/SequelizeConfigFactory
      method: 'createConfig'

  Shared.SequelizeConnectionManager:
    factory:
      class: ../../../main/shared/infrastructure/sequelize/SequelizeClientFactory
      method: 'createClient'
    arguments: ['@Shared.SequelizeConfig']

  Shared.Logger:
    class: ../../main/shared/infrastructure/logger/WinstonLogger
    arguments: []

  Shared.CommandHandlersInformation:
    class: ../../main/shared/infrastructure/bus/command/CommandHandlers
    arguments: ['!tagged commandHandler']

  Shared.CommandBus:
    class: ../../main/shared/infrastructure/bus/command/InMemoryCommandBus
    arguments: ['@Shared.CommandHandlersInformation']

  Shared.QueryHandlersInformation:
    class: ../../main/shared/infrastructure/bus/query/QueryHandlers
    arguments: ['!tagged queryHandler']

  Shared.QueryBus:
    class: ../../main/shared/infrastructure/bus/query/InMemoryQueryBus
    arguments: ['@Shared.QueryHandlersInformation']
